sudo: false

language: node_js

node_js:
  - '6'

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm run lint
  - npm test
  - SL=true npm test
  - npm build
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

install:
  - npm install

cache:
  directories:
    - node_modules

# Necessary to compile native modules for io.js v3 or Node.js v4
env:
  - CXX=g++-4.8

# Necessary to compile native modules for io.js v3 or Node.js v4
addons:
  sauce_connect: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
